openapi: 3.0.3
info:
  title: Mental Models API
  description: REST API for mental model management in Dionysus
  version: 1.0.0
  contact:
    name: Dionysus Core Team

servers:
  - url: http://localhost:8000
    description: Local development

paths:
  /api/models:
    get:
      summary: List mental models
      operationId: listModels
      tags:
        - Models
      parameters:
        - name: domain
          in: query
          schema:
            type: string
            enum: [user, self, world, task_specific]
        - name: status
          in: query
          schema:
            type: string
            enum: [draft, active, deprecated]
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: List of models
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelListResponse'

    post:
      summary: Create a mental model
      operationId: createModel
      tags:
        - Models
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateModelRequest'
      responses:
        '201':
          description: Model created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Validation error (e.g., invalid basin IDs)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/models/{model_id}:
    parameters:
      - name: model_id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: Get model details
      operationId: getModel
      tags:
        - Models
      responses:
        '200':
          description: Model details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelDetailResponse'
        '404':
          description: Model not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Update a model
      operationId: updateModel
      tags:
        - Models
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateModelRequest'
      responses:
        '200':
          description: Model updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelResponse'
        '404':
          description: Model not found
        '422':
          description: Validation error

    delete:
      summary: Deprecate a model (soft delete)
      operationId: deprecateModel
      tags:
        - Models
      responses:
        '200':
          description: Model deprecated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelResponse'
        '404':
          description: Model not found

  /api/models/{model_id}/predictions:
    parameters:
      - name: model_id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: List predictions for a model
      operationId: listModelPredictions
      tags:
        - Predictions
      parameters:
        - name: resolved
          in: query
          description: Filter by resolution status
          schema:
            type: boolean
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of predictions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PredictionListResponse'
        '404':
          description: Model not found

  /api/models/{model_id}/revisions:
    parameters:
      - name: model_id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: List revision history for a model
      operationId: listModelRevisions
      tags:
        - Revisions
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of revisions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RevisionListResponse'
        '404':
          description: Model not found

    post:
      summary: Trigger model revision
      operationId: reviseModel
      tags:
        - Revisions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviseModelRequest'
      responses:
        '201':
          description: Revision created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RevisionResponse'
        '404':
          description: Model not found
        '422':
          description: Validation error

components:
  schemas:
    CreateModelRequest:
      type: object
      required:
        - name
        - domain
        - basin_ids
      properties:
        name:
          type: string
          maxLength: 255
        domain:
          type: string
          enum: [user, self, world, task_specific]
        basin_ids:
          type: array
          items:
            type: string
            format: uuid
          minItems: 1
        description:
          type: string
        prediction_templates:
          type: array
          items:
            $ref: '#/components/schemas/PredictionTemplate'

    UpdateModelRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
        description:
          type: string
        status:
          type: string
          enum: [draft, active, deprecated]
        prediction_templates:
          type: array
          items:
            $ref: '#/components/schemas/PredictionTemplate'

    ReviseModelRequest:
      type: object
      required:
        - trigger_description
      properties:
        trigger_description:
          type: string
        add_basins:
          type: array
          items:
            type: string
            format: uuid
        remove_basins:
          type: array
          items:
            type: string
            format: uuid

    PredictionTemplate:
      type: object
      properties:
        trigger:
          type: string
        predict:
          type: string
        suggest:
          type: string

    ModelResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        domain:
          type: string
        status:
          type: string
        prediction_accuracy:
          type: number
        basin_count:
          type: integer
        revision_count:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ModelDetailResponse:
      allOf:
        - $ref: '#/components/schemas/ModelResponse'
        - type: object
          properties:
            description:
              type: string
            constituent_basins:
              type: array
              items:
                type: string
                format: uuid
            basin_relationships:
              type: object
            prediction_templates:
              type: array
              items:
                $ref: '#/components/schemas/PredictionTemplate'
            evidence_memories:
              type: array
              items:
                type: string
                format: uuid

    ModelListResponse:
      type: object
      properties:
        models:
          type: array
          items:
            $ref: '#/components/schemas/ModelResponse'
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer

    PredictionResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        model_id:
          type: string
          format: uuid
        prediction:
          type: object
        confidence:
          type: number
        context:
          type: object
        observation:
          type: object
        prediction_error:
          type: number
        resolved_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time

    PredictionListResponse:
      type: object
      properties:
        predictions:
          type: array
          items:
            $ref: '#/components/schemas/PredictionResponse'
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer

    RevisionResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        model_id:
          type: string
          format: uuid
        trigger_type:
          type: string
          enum: [prediction_error, new_evidence, contradiction, manual]
        trigger_description:
          type: string
        basins_added:
          type: array
          items:
            type: string
            format: uuid
        basins_removed:
          type: array
          items:
            type: string
            format: uuid
        change_description:
          type: string
        prediction_error_before:
          type: number
        prediction_error_after:
          type: number
        created_at:
          type: string
          format: date-time

    RevisionListResponse:
      type: object
      properties:
        revisions:
          type: array
          items:
            $ref: '#/components/schemas/RevisionResponse'
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        code:
          type: string
        details:
          type: object
