openapi: 3.1.0
info:
  title: Metacognitive Particles API
  version: 1.0.0
  description: |
    API for metacognitive particle classification, mental actions,
    sense of agency computation, and epistemic gain detection.
    Based on Sandved-Smith & Da Costa (2024) and Seragnoli et al. (2025).

servers:
  - url: /api/v1
    description: Dionysus API

paths:
  /metacognition/classify:
    post:
      operationId: classifyParticle
      summary: Classify a cognitive process into particle type
      description: |
        Analyzes Markov blanket structure to determine particle type.
        Returns classification with confidence score.
      tags:
        - Classification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClassifyRequest'
      responses:
        '200':
          description: Classification result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassificationResult'
        '400':
          description: Invalid blanket structure
        '422':
          description: Validation error

  /metacognition/mental-action:
    post:
      operationId: executeMentalAction
      summary: Execute a mental action on target agent
      description: |
        Higher-level mental action modulating lower-level precision or spotlight.
        Tracks prior and post-modulation states.
      tags:
        - Mental Actions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MentalActionRequest'
      responses:
        '200':
          description: Mental action executed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MentalActionResult'
        '400':
          description: Invalid action type or target
        '403':
          description: Hierarchy violation (cannot target higher-level)

  /metacognition/agency/{agent_id}:
    get:
      operationId: getAgencyStrength
      summary: Get sense of agency strength for an agent
      description: |
        Computes KL divergence D_KL[Q(μ,a) | Q(μ)Q(a)] as agency measure.
        Returns 0.0 for no agency, higher values for stronger agency sense.
      tags:
        - Agency
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Agency strength computed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgencyResult'
        '404':
          description: Agent not found

  /metacognition/epistemic-gain/check:
    post:
      operationId: checkEpistemicGain
      summary: Check for epistemic gain event
      description: |
        Compares prior and posterior beliefs to detect "Aha!" moments.
        Returns event if uncertainty reduction exceeds threshold.
      tags:
        - Epistemic Gain
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EpistemicGainCheckRequest'
      responses:
        '200':
          description: Check result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EpistemicGainCheckResult'
        '400':
          description: Invalid belief states

  /metacognition/monitoring/{agent_id}:
    get:
      operationId: getMonitoringAssessment
      summary: Get cognitive assessment for an agent
      description: |
        Non-invasive monitoring of cognitive state.
        Returns progress, confidence, issues, and recommendations.
      tags:
        - Procedural Metacognition
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Assessment result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CognitiveAssessment'
        '404':
          description: Agent not found

  /metacognition/control:
    post:
      operationId: applyControlAction
      summary: Apply control action based on assessment
      description: |
        Takes cognitive assessment and returns recommended mental actions
        to regulate cognition.
      tags:
        - Procedural Metacognition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ControlRequest'
      responses:
        '200':
          description: Control actions recommended
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ControlResult'

components:
  schemas:
    ParticleType:
      type: string
      enum:
        - cognitive
        - passive_metacognitive
        - active_metacognitive
        - strange_metacognitive
        - nested_n_level

    MentalActionType:
      type: string
      enum:
        - precision_delta
        - set_precision
        - focus_target
        - spotlight_precision

    ClassifyRequest:
      type: object
      required:
        - agent_id
        - blanket
      properties:
        agent_id:
          type: string
          description: Agent identifier
        blanket:
          $ref: '#/components/schemas/MarkovBlanketInput'

    MarkovBlanketInput:
      type: object
      required:
        - external_paths
        - sensory_paths
        - active_paths
        - internal_paths
      properties:
        external_paths:
          type: array
          items:
            type: string
        sensory_paths:
          type: array
          items:
            type: string
        active_paths:
          type: array
          items:
            type: string
        internal_paths:
          type: array
          items:
            type: string

    ClassificationResult:
      type: object
      properties:
        particle_id:
          type: string
          format: uuid
        particle_type:
          $ref: '#/components/schemas/ParticleType'
        confidence:
          type: number
          minimum: 0.0
          maximum: 1.0
        level:
          type: integer
          minimum: 0
        has_agency:
          type: boolean
        classified_at:
          type: string
          format: date-time

    MentalActionRequest:
      type: object
      required:
        - source_agent
        - target_agent
        - action_type
        - modulation
      properties:
        source_agent:
          type: string
        target_agent:
          type: string
        action_type:
          $ref: '#/components/schemas/MentalActionType'
        modulation:
          type: object
          additionalProperties: true
          description: Action-specific parameters

    MentalActionResult:
      type: object
      properties:
        action_id:
          type: string
          format: uuid
        success:
          type: boolean
        prior_state:
          type: object
        new_state:
          type: object
        modulations_applied:
          type: array
          items:
            type: string
        executed_at:
          type: string
          format: date-time

    AgencyResult:
      type: object
      properties:
        agent_id:
          type: string
        agency_strength:
          type: number
          minimum: 0.0
          description: KL divergence value (0 = no agency)
        has_agency:
          type: boolean
        particle_type:
          $ref: '#/components/schemas/ParticleType'
        computed_at:
          type: string
          format: date-time

    BeliefStateInput:
      type: object
      required:
        - mean
        - precision
      properties:
        mean:
          type: array
          items:
            type: number
        precision:
          type: array
          items:
            type: array
            items:
              type: number
        entropy:
          type: number
          description: Optional, will be computed if not provided

    EpistemicGainCheckRequest:
      type: object
      required:
        - particle_id
        - prior_belief
        - posterior_belief
      properties:
        particle_id:
          type: string
          format: uuid
        prior_belief:
          $ref: '#/components/schemas/BeliefStateInput'
        posterior_belief:
          $ref: '#/components/schemas/BeliefStateInput'
        threshold:
          type: number
          default: 0.3
          description: Minimum uncertainty reduction to trigger event

    EpistemicGainCheckResult:
      type: object
      properties:
        gain_detected:
          type: boolean
        event:
          $ref: '#/components/schemas/EpistemicGainEvent'
          nullable: true

    EpistemicGainEvent:
      type: object
      properties:
        id:
          type: string
          format: uuid
        magnitude:
          type: number
          minimum: 0.0
          maximum: 1.0
        prior_entropy:
          type: number
        posterior_entropy:
          type: number
        noetic_quality:
          type: boolean
          description: True if certainty without proportional evidence
        detected_at:
          type: string
          format: date-time

    CognitiveAssessment:
      type: object
      properties:
        id:
          type: string
          format: uuid
        agent_id:
          type: string
        progress:
          type: number
          minimum: 0.0
          maximum: 1.0
        confidence:
          type: number
          minimum: 0.0
          maximum: 1.0
        prediction_error:
          type: number
        issues:
          type: array
          items:
            type: string
        recommendations:
          type: array
          items:
            type: string
        assessed_at:
          type: string
          format: date-time

    ControlRequest:
      type: object
      required:
        - assessment
      properties:
        assessment:
          $ref: '#/components/schemas/CognitiveAssessment'

    ControlResult:
      type: object
      properties:
        recommended_actions:
          type: array
          items:
            $ref: '#/components/schemas/MentalActionRequest'
        rationale:
          type: string
          description: Explanation for recommended actions

tags:
  - name: Classification
    description: Particle type classification
  - name: Mental Actions
    description: Precision and attention modulation
  - name: Agency
    description: Sense of agency computation
  - name: Epistemic Gain
    description: Learning detection ("Aha!" moments)
  - name: Procedural Metacognition
    description: Monitoring and control functions
